---
- name: Include common docker tasks
  include_role:
    name: common
    tasks_from: docker

- name: Include common kubernetes tasks
  include_role:
    name: common
    tasks_from: kubernetes

- name: Include Kubernetes installation tasks
  include_tasks: master-components.yaml

- name: Include Flannel setup
  include_tasks: flannel.yml